#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WcfService.Repositories
{
	using Telerik.OpenAccess;
	using DataLayer;
	using System;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Collections;
	using System.Collections.Generic;
	using System.Runtime.Serialization;

	
	public partial interface IRepository<TEntity>
	{
	    void Add(TEntity entity);
	    void Remove(TEntity entity);
	
	    TEntity Get(ObjectKey objectKey);
	    
	    IQueryable<TEntity> GetAll();
	
	    IQueryable<TEntity> Find(Expression<Func<TEntity, bool>> predicate);
	}
	
	public partial class Repository<TEntity> : IRepository<TEntity>
	        where TEntity : class
	{
	    protected IUnitOfWork unitOfWork;
	
	    public Repository(IUnitOfWork unitOfWork)
	    {
	        this.unitOfWork = unitOfWork;
	    }
	
	    public void Add(TEntity entity)
	    {
			this.unitOfWork.Add(entity);
	    }
	
	    public void Remove(TEntity entity)
	    {
	        this.unitOfWork.Delete(entity);
	    }
	
	    public IQueryable<TEntity> GetAll()
	    {
	        return this.unitOfWork.GetAll<TEntity>();
	    }
	
	    public TEntity Get(ObjectKey objectKey)
	    {
	        return this.unitOfWork.GetObjectByKey<TEntity>(objectKey);
	    }
	
	    public IQueryable<TEntity> Find(Expression<Func<TEntity, bool>> predicate)
	    {
	        return this.unitOfWork.GetAll<TEntity>().Where(predicate);
	    }
	}
	
	public partial interface IConsultazioneRepository : IRepository<Consultazione>
	{ 
	
	}
	
	public partial class ConsultazioneRepository : Repository<Consultazione>, IConsultazioneRepository
	{
	    public ConsultazioneRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface ICapoCoalizioneRepository : IRepository<CapoCoalizione>
	{ 
	
	}
	
	public partial class CapoCoalizioneRepository : Repository<CapoCoalizione>, ICapoCoalizioneRepository
	{
	    public CapoCoalizioneRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IListaRepository : IRepository<Lista>
	{ 
	
	}
	
	public partial class ListaRepository : Repository<Lista>, IListaRepository
	{
	    public ListaRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface ICandidatoRepository : IRepository<Candidato>
	{ 
	
	}
	
	public partial class CandidatoRepository : Repository<Candidato>, ICandidatoRepository
	{
	    public CandidatoRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface ISedeElettoraleRepository : IRepository<SedeElettorale>
	{ 
	
	}
	
	public partial class SedeElettoraleRepository : Repository<SedeElettorale>, ISedeElettoraleRepository
	{
	    public SedeElettoraleRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface ISezioneRepository : IRepository<Sezione>
	{ 
	
	}
	
	public partial class SezioneRepository : Repository<Sezione>, ISezioneRepository
	{
	    public SezioneRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IAffluenzaRepository : IRepository<Affluenza>
	{ 
	
	}
	
	public partial class AffluenzaRepository : Repository<Affluenza>, IAffluenzaRepository
	{
	    public AffluenzaRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IComuneRepository : IRepository<Comune>
	{ 
	
	}
	
	public partial class ComuneRepository : Repository<Comune>, IComuneRepository
	{
	    public ComuneRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface ICollegioRepository : IRepository<Collegio>
	{ 
	
	}
	
	public partial class CollegioRepository : Repository<Collegio>, ICollegioRepository
	{
	    public CollegioRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface ISezioneCollegioRepository : IRepository<SezioneCollegio>
	{ 
	
	}
	
	public partial class SezioneCollegioRepository : Repository<SezioneCollegio>, ISezioneCollegioRepository
	{
	    public SezioneCollegioRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IRilevamentoRepository : IRepository<Rilevamento>
	{ 
	
	}
	
	public partial class RilevamentoRepository : Repository<Rilevamento>, IRilevamentoRepository
	{
	    public RilevamentoRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IScrutinioCapoCoalizioneRepository : IRepository<ScrutinioCapoCoalizione>
	{ 
	
	}
	
	public partial class ScrutinioCapoCoalizioneRepository : Repository<ScrutinioCapoCoalizione>, IScrutinioCapoCoalizioneRepository
	{
	    public ScrutinioCapoCoalizioneRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IScrutinioRepository : IRepository<Scrutinio>
	{ 
	
	}
	
	public partial class ScrutinioRepository : Repository<Scrutinio>, IScrutinioRepository
	{
	    public ScrutinioRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IScrutinioListaRepository : IRepository<ScrutinioLista>
	{ 
	
	}
	
	public partial class ScrutinioListaRepository : Repository<ScrutinioLista>, IScrutinioListaRepository
	{
	    public ScrutinioListaRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IScrutinioCandidatoRepository : IRepository<ScrutinioCandidato>
	{ 
	
	}
	
	public partial class ScrutinioCandidatoRepository : Repository<ScrutinioCandidato>, IScrutinioCandidatoRepository
	{
	    public ScrutinioCandidatoRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
	
	public partial interface IOperatoreRepository : IRepository<Operatore>
	{ 
	
	}
	
	public partial class OperatoreRepository : Repository<Operatore>, IOperatoreRepository
	{
	    public OperatoreRepository(IEntitiesModelUnitOfWork unitOfWork)
	        : base(unitOfWork)
	    {
	    }
	}
}
#pragma warning restore 1591
