#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using DataLayer;
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace WcfService.Dto
{
	public interface IDtoWithKey
	{
		string DtoKey { get; set; }
	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ComuneDto))]
	[KnownType(typeof(CollegioDto))]
	[KnownType(typeof(AffluenzaDto))]
	[KnownType(typeof(ScrutinioDto))]
	[KnownType(typeof(SedeElettoraleDto))]
	[KnownType(typeof(OperatoreDto))]
	[KnownType(typeof(CapoCoalizioneDto))]
	public partial class ConsultazioneDto : IDtoWithKey
	{
		public ConsultazioneDto()
		{
		}
		
		public ConsultazioneDto(int _id, int _numero, string _descrizione, string _tipo, int _comuneId, ComuneDto _comune, IList<CollegioDto> _collegios, IList<AffluenzaDto> _affluenzas, IList<ScrutinioDto> _scrutinios, IList<SedeElettoraleDto> _sedeElettorales, IList<OperatoreDto> _operatores, IList<CapoCoalizioneDto> _capoCoaliziones)
		{
			this.Id = _id;
			this.Numero = _numero;
			this.Descrizione = _descrizione;
			this.Tipo = _tipo;
			this.ComuneId = _comuneId;
			this.Comune = _comune;
			this.Collegios = _collegios;
			this.Affluenzas = _affluenzas;
			this.Scrutinios = _scrutinios;
			this.SedeElettorales = _sedeElettorales;
			this.Operatores = _operatores;
			this.CapoCoaliziones = _capoCoaliziones;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int Numero { get;set; }

		[DataMember]
		public virtual string Descrizione { get;set; }

		[DataMember]
		public virtual string Tipo { get;set; }

		[DataMember]
		public virtual int ComuneId { get;set; }

		[DataMember]
		public virtual ComuneDto Comune { get;set; }

		[DataMember]
		public virtual IList<CollegioDto> Collegios { get;set; }

		[DataMember]
		public virtual IList<AffluenzaDto> Affluenzas { get;set; }

		[DataMember]
		public virtual IList<ScrutinioDto> Scrutinios { get;set; }

		[DataMember]
		public virtual IList<SedeElettoraleDto> SedeElettorales { get;set; }

		[DataMember]
		public virtual IList<OperatoreDto> Operatores { get;set; }

		[DataMember]
		public virtual IList<CapoCoalizioneDto> CapoCoaliziones { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ConsultazioneDto))]
	[KnownType(typeof(ListaDto))]
	[KnownType(typeof(ScrutinioCapoCoalizioneDto))]
	public partial class CapoCoalizioneDto : IDtoWithKey
	{
		public CapoCoalizioneDto()
		{
		}
		
		public CapoCoalizioneDto(int _id, int? _numero, string _descrizione, string _simbolo, int _consultazioneId, ConsultazioneDto _consultazione, IList<ListaDto> _listas, IList<ScrutinioCapoCoalizioneDto> _scrutinioCapoCoaliziones)
		{
			this.Id = _id;
			this.Numero = _numero;
			this.Descrizione = _descrizione;
			this.Simbolo = _simbolo;
			this.ConsultazioneId = _consultazioneId;
			this.Consultazione = _consultazione;
			this.Listas = _listas;
			this.ScrutinioCapoCoaliziones = _scrutinioCapoCoaliziones;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int? Numero { get;set; }

		[DataMember]
		public virtual string Descrizione { get;set; }

		[DataMember]
		public virtual string Simbolo { get;set; }

		[DataMember]
		public virtual int ConsultazioneId { get;set; }

		[DataMember]
		public virtual ConsultazioneDto Consultazione { get;set; }

		[DataMember]
		public virtual IList<ListaDto> Listas { get;set; }

		[DataMember]
		public virtual IList<ScrutinioCapoCoalizioneDto> ScrutinioCapoCoaliziones { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(CapoCoalizioneDto))]
	[KnownType(typeof(CandidatoDto))]
	[KnownType(typeof(ScrutinioListaDto))]
	public partial class ListaDto : IDtoWithKey
	{
		public ListaDto()
		{
		}
		
		public ListaDto(int _id, int _capoCoalizioneId, int? _numero, string _descrizione, string _simbolo, CapoCoalizioneDto _capoCoalizione, IList<CandidatoDto> _candidatos, IList<ScrutinioListaDto> _scrutinioListas)
		{
			this.Id = _id;
			this.CapoCoalizioneId = _capoCoalizioneId;
			this.Numero = _numero;
			this.Descrizione = _descrizione;
			this.Simbolo = _simbolo;
			this.CapoCoalizione = _capoCoalizione;
			this.Candidatos = _candidatos;
			this.ScrutinioListas = _scrutinioListas;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int CapoCoalizioneId { get;set; }

		[DataMember]
		public virtual int? Numero { get;set; }

		[DataMember]
		public virtual string Descrizione { get;set; }

		[DataMember]
		public virtual string Simbolo { get;set; }

		[DataMember]
		public virtual CapoCoalizioneDto CapoCoalizione { get;set; }

		[DataMember]
		public virtual IList<CandidatoDto> Candidatos { get;set; }

		[DataMember]
		public virtual IList<ScrutinioListaDto> ScrutinioListas { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ListaDto))]
	[KnownType(typeof(ScrutinioCandidatoDto))]
	public partial class CandidatoDto : IDtoWithKey
	{
		public CandidatoDto()
		{
		}
		
		public CandidatoDto(int _id, int _listaId, int? _numero, string _cognome, string _nome, ListaDto _lista, IList<ScrutinioCandidatoDto> _scrutinioCandidatos)
		{
			this.Id = _id;
			this.ListaId = _listaId;
			this.Numero = _numero;
			this.Cognome = _cognome;
			this.Nome = _nome;
			this.Lista = _lista;
			this.ScrutinioCandidatos = _scrutinioCandidatos;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int ListaId { get;set; }

		[DataMember]
		public virtual int? Numero { get;set; }

		[DataMember]
		public virtual string Cognome { get;set; }

		[DataMember]
		public virtual string Nome { get;set; }

		[DataMember]
		public virtual ListaDto Lista { get;set; }

		[DataMember]
		public virtual IList<ScrutinioCandidatoDto> ScrutinioCandidatos { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ConsultazioneDto))]
	[KnownType(typeof(SezioneDto))]
	public partial class SedeElettoraleDto : IDtoWithKey
	{
		public SedeElettoraleDto()
		{
		}
		
		public SedeElettoraleDto(int _id, string _indirizzo, string _mappa, string _telefono, string _fax, string _responsabile, int _consultazioneId, ConsultazioneDto _consultazione, IList<SezioneDto> _seziones)
		{
			this.Id = _id;
			this.Indirizzo = _indirizzo;
			this.Mappa = _mappa;
			this.Telefono = _telefono;
			this.Fax = _fax;
			this.Responsabile = _responsabile;
			this.ConsultazioneId = _consultazioneId;
			this.Consultazione = _consultazione;
			this.Seziones = _seziones;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string Indirizzo { get;set; }

		[DataMember]
		public virtual string Mappa { get;set; }

		[DataMember]
		public virtual string Telefono { get;set; }

		[DataMember]
		public virtual string Fax { get;set; }

		[DataMember]
		public virtual string Responsabile { get;set; }

		[DataMember]
		public virtual int ConsultazioneId { get;set; }

		[DataMember]
		public virtual ConsultazioneDto Consultazione { get;set; }

		[DataMember]
		public virtual IList<SezioneDto> Seziones { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(SedeElettoraleDto))]
	[KnownType(typeof(OperatoreDto))]
	[KnownType(typeof(SezioneCollegioDto))]
	[KnownType(typeof(RilevamentoDto))]
	[KnownType(typeof(ScrutinioDto))]
	[KnownType(typeof(ScrutinioListaDto))]
	[KnownType(typeof(ScrutinioCandidatoDto))]
	[KnownType(typeof(ScrutinioCapoCoalizioneDto))]
	public partial class SezioneDto : IDtoWithKey
	{
		public SezioneDto()
		{
		}
		
		public SezioneDto(int _id, int? _votantiMaschi, int? _votantiFemmine, int? _totaleVotanti, int _sedeElettoraleId, int _operatoreId, string _numero, SedeElettoraleDto _sedeElettorale, OperatoreDto _operatore, IList<SezioneCollegioDto> _sezioneCollegios, IList<RilevamentoDto> _rilevamentos, IList<ScrutinioDto> _scrutinios, IList<ScrutinioListaDto> _scrutinioListas, IList<ScrutinioCandidatoDto> _scrutinioCandidatos, IList<ScrutinioCapoCoalizioneDto> _scrutinioCapoCoaliziones)
		{
			this.Id = _id;
			this.VotantiMaschi = _votantiMaschi;
			this.VotantiFemmine = _votantiFemmine;
			this.TotaleVotanti = _totaleVotanti;
			this.SedeElettoraleId = _sedeElettoraleId;
			this.OperatoreId = _operatoreId;
			this.Numero = _numero;
			this.SedeElettorale = _sedeElettorale;
			this.Operatore = _operatore;
			this.SezioneCollegios = _sezioneCollegios;
			this.Rilevamentos = _rilevamentos;
			this.Scrutinios = _scrutinios;
			this.ScrutinioListas = _scrutinioListas;
			this.ScrutinioCandidatos = _scrutinioCandidatos;
			this.ScrutinioCapoCoaliziones = _scrutinioCapoCoaliziones;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int? VotantiMaschi { get;set; }

		[DataMember]
		public virtual int? VotantiFemmine { get;set; }

		[DataMember]
		public virtual int? TotaleVotanti { get;set; }

		[DataMember]
		public virtual int SedeElettoraleId { get;set; }

		[DataMember]
		public virtual int OperatoreId { get;set; }

		[DataMember]
		public virtual string Numero { get;set; }

		[DataMember]
		public virtual SedeElettoraleDto SedeElettorale { get;set; }

		[DataMember]
		public virtual OperatoreDto Operatore { get;set; }

		[DataMember]
		public virtual IList<SezioneCollegioDto> SezioneCollegios { get;set; }

		[DataMember]
		public virtual IList<RilevamentoDto> Rilevamentos { get;set; }

		[DataMember]
		public virtual IList<ScrutinioDto> Scrutinios { get;set; }

		[DataMember]
		public virtual IList<ScrutinioListaDto> ScrutinioListas { get;set; }

		[DataMember]
		public virtual IList<ScrutinioCandidatoDto> ScrutinioCandidatos { get;set; }

		[DataMember]
		public virtual IList<ScrutinioCapoCoalizioneDto> ScrutinioCapoCoaliziones { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ConsultazioneDto))]
	[KnownType(typeof(RilevamentoDto))]
	public partial class AffluenzaDto : IDtoWithKey
	{
		public AffluenzaDto()
		{
		}
		
		public AffluenzaDto(int _id, int _consultazioneId, DateTime _orario, ConsultazioneDto _consultazione, IList<RilevamentoDto> _rilevamentos)
		{
			this.Id = _id;
			this.ConsultazioneId = _consultazioneId;
			this.Orario = _orario;
			this.Consultazione = _consultazione;
			this.Rilevamentos = _rilevamentos;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int ConsultazioneId { get;set; }

		[DataMember]
		public virtual DateTime Orario { get;set; }

		[DataMember]
		public virtual ConsultazioneDto Consultazione { get;set; }

		[DataMember]
		public virtual IList<RilevamentoDto> Rilevamentos { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ConsultazioneDto))]
	public partial class ComuneDto : IDtoWithKey
	{
		public ComuneDto()
		{
		}
		
		public ComuneDto(int _id, string _descrizione, string _nome, string _provincia, string _codiceISTAT, int? _numeroSezioni, IList<ConsultazioneDto> _consultaziones)
		{
			this.Id = _id;
			this.Descrizione = _descrizione;
			this.Nome = _nome;
			this.Provincia = _provincia;
			this.CodiceISTAT = _codiceISTAT;
			this.NumeroSezioni = _numeroSezioni;
			this.Consultaziones = _consultaziones;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string Descrizione { get;set; }

		[DataMember]
		public virtual string Nome { get;set; }

		[DataMember]
		public virtual string Provincia { get;set; }

		[DataMember]
		public virtual string CodiceISTAT { get;set; }

		[DataMember]
		public virtual int? NumeroSezioni { get;set; }

		[DataMember]
		public virtual IList<ConsultazioneDto> Consultaziones { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ConsultazioneDto))]
	[KnownType(typeof(SezioneCollegioDto))]
	public partial class CollegioDto : IDtoWithKey
	{
		public CollegioDto()
		{
		}
		
		public CollegioDto(int _id, int _consultazioneId, int? _numero, string _descrizione, ConsultazioneDto _consultazione, IList<SezioneCollegioDto> _sezioneCollegios)
		{
			this.Id = _id;
			this.ConsultazioneId = _consultazioneId;
			this.Numero = _numero;
			this.Descrizione = _descrizione;
			this.Consultazione = _consultazione;
			this.SezioneCollegios = _sezioneCollegios;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int ConsultazioneId { get;set; }

		[DataMember]
		public virtual int? Numero { get;set; }

		[DataMember]
		public virtual string Descrizione { get;set; }

		[DataMember]
		public virtual ConsultazioneDto Consultazione { get;set; }

		[DataMember]
		public virtual IList<SezioneCollegioDto> SezioneCollegios { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(SezioneDto))]
	[KnownType(typeof(CollegioDto))]
	public partial class SezioneCollegioDto : IDtoWithKey
	{
		public SezioneCollegioDto()
		{
		}
		
		public SezioneCollegioDto(int _id, int _sezioneId, int _collegioId, SezioneDto _sezione, CollegioDto _collegio)
		{
			this.Id = _id;
			this.SezioneId = _sezioneId;
			this.CollegioId = _collegioId;
			this.Sezione = _sezione;
			this.Collegio = _collegio;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int SezioneId { get;set; }

		[DataMember]
		public virtual int CollegioId { get;set; }

		[DataMember]
		public virtual SezioneDto Sezione { get;set; }

		[DataMember]
		public virtual CollegioDto Collegio { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(SezioneDto))]
	[KnownType(typeof(AffluenzaDto))]
	public partial class RilevamentoDto : IDtoWithKey
	{
		public RilevamentoDto()
		{
		}
		
		public RilevamentoDto(int _id, int? _uomini, int? _donne, int? _totale, int _affluenzaId, int _sezioneId, SezioneDto _sezione, AffluenzaDto _affluenza)
		{
			this.Id = _id;
			this.Uomini = _uomini;
			this.Donne = _donne;
			this.Totale = _totale;
			this.AffluenzaId = _affluenzaId;
			this.SezioneId = _sezioneId;
			this.Sezione = _sezione;
			this.Affluenza = _affluenza;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int? Uomini { get;set; }

		[DataMember]
		public virtual int? Donne { get;set; }

		[DataMember]
		public virtual int? Totale { get;set; }

		[DataMember]
		public virtual int AffluenzaId { get;set; }

		[DataMember]
		public virtual int SezioneId { get;set; }

		[DataMember]
		public virtual SezioneDto Sezione { get;set; }

		[DataMember]
		public virtual AffluenzaDto Affluenza { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(CapoCoalizioneDto))]
	[KnownType(typeof(SezioneDto))]
	public partial class ScrutinioCapoCoalizioneDto : IDtoWithKey
	{
		public ScrutinioCapoCoalizioneDto()
		{
		}
		
		public ScrutinioCapoCoalizioneDto(int _id, int _capoCoalizioneId, int _sezioneId, int? _voti, int? _votiAnnullati, CapoCoalizioneDto _capoCoalizione, SezioneDto _sezione)
		{
			this.Id = _id;
			this.CapoCoalizioneId = _capoCoalizioneId;
			this.SezioneId = _sezioneId;
			this.Voti = _voti;
			this.VotiAnnullati = _votiAnnullati;
			this.CapoCoalizione = _capoCoalizione;
			this.Sezione = _sezione;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int CapoCoalizioneId { get;set; }

		[DataMember]
		public virtual int SezioneId { get;set; }

		[DataMember]
		public virtual int? Voti { get;set; }

		[DataMember]
		public virtual int? VotiAnnullati { get;set; }

		[DataMember]
		public virtual CapoCoalizioneDto CapoCoalizione { get;set; }

		[DataMember]
		public virtual SezioneDto Sezione { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(SezioneDto))]
	[KnownType(typeof(ConsultazioneDto))]
	public partial class ScrutinioDto : IDtoWithKey
	{
		public ScrutinioDto()
		{
		}
		
		public ScrutinioDto(int _id, int? _validi, int? _nulle, int? _bianche, int? _contestate, int? _sezioneId, int? _consultazioneId, SezioneDto _sezione, ConsultazioneDto _consultazione)
		{
			this.Id = _id;
			this.Validi = _validi;
			this.Nulle = _nulle;
			this.Bianche = _bianche;
			this.Contestate = _contestate;
			this.SezioneId = _sezioneId;
			this.ConsultazioneId = _consultazioneId;
			this.Sezione = _sezione;
			this.Consultazione = _consultazione;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int? Validi { get;set; }

		[DataMember]
		public virtual int? Nulle { get;set; }

		[DataMember]
		public virtual int? Bianche { get;set; }

		[DataMember]
		public virtual int? Contestate { get;set; }

		[DataMember]
		public virtual int? SezioneId { get;set; }

		[DataMember]
		public virtual int? ConsultazioneId { get;set; }

		[DataMember]
		public virtual SezioneDto Sezione { get;set; }

		[DataMember]
		public virtual ConsultazioneDto Consultazione { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(SezioneDto))]
	[KnownType(typeof(ListaDto))]
	public partial class ScrutinioListaDto : IDtoWithKey
	{
		public ScrutinioListaDto()
		{
		}
		
		public ScrutinioListaDto(int _id, int? _voti, int _listaId, int _sezioneId, int? _votiAnnullati, SezioneDto _sezione, ListaDto _lista)
		{
			this.Id = _id;
			this.Voti = _voti;
			this.ListaId = _listaId;
			this.SezioneId = _sezioneId;
			this.VotiAnnullati = _votiAnnullati;
			this.Sezione = _sezione;
			this.Lista = _lista;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int? Voti { get;set; }

		[DataMember]
		public virtual int ListaId { get;set; }

		[DataMember]
		public virtual int SezioneId { get;set; }

		[DataMember]
		public virtual int? VotiAnnullati { get;set; }

		[DataMember]
		public virtual SezioneDto Sezione { get;set; }

		[DataMember]
		public virtual ListaDto Lista { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(SezioneDto))]
	[KnownType(typeof(CandidatoDto))]
	public partial class ScrutinioCandidatoDto : IDtoWithKey
	{
		public ScrutinioCandidatoDto()
		{
		}
		
		public ScrutinioCandidatoDto(int _id, int _voti, int _sezioneId, int? _candidatoId, int? _votiAnnullati, SezioneDto _sezione, CandidatoDto _candidato)
		{
			this.Id = _id;
			this.Voti = _voti;
			this.SezioneId = _sezioneId;
			this.CandidatoId = _candidatoId;
			this.VotiAnnullati = _votiAnnullati;
			this.Sezione = _sezione;
			this.Candidato = _candidato;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int Voti { get;set; }

		[DataMember]
		public virtual int SezioneId { get;set; }

		[DataMember]
		public virtual int? CandidatoId { get;set; }

		[DataMember]
		public virtual int? VotiAnnullati { get;set; }

		[DataMember]
		public virtual SezioneDto Sezione { get;set; }

		[DataMember]
		public virtual CandidatoDto Candidato { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(ConsultazioneDto))]
	[KnownType(typeof(SezioneDto))]
	public partial class OperatoreDto : IDtoWithKey
	{
		public OperatoreDto()
		{
		}
		
		public OperatoreDto(int _id, string _username, string _password, string _confermaPassword, string _email, string _telefono, string _cognome, string _nome, int _consultazioneId, bool _supervisor, bool _amministratore, bool _utente, ConsultazioneDto _consultazione, IList<SezioneDto> _seziones)
		{
			this.Id = _id;
			this.Username = _username;
			this.Password = _password;
			this.ConfermaPassword = _confermaPassword;
			this.Email = _email;
			this.Telefono = _telefono;
			this.Cognome = _cognome;
			this.Nome = _nome;
			this.ConsultazioneId = _consultazioneId;
			this.Supervisor = _supervisor;
			this.Amministratore = _amministratore;
			this.Utente = _utente;
			this.Consultazione = _consultazione;
			this.Seziones = _seziones;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual string Username { get;set; }

		[DataMember]
		public virtual string Password { get;set; }

		[DataMember]
		public virtual string ConfermaPassword { get;set; }

		[DataMember]
		public virtual string Email { get;set; }

		[DataMember]
		public virtual string Telefono { get;set; }

		[DataMember]
		public virtual string Cognome { get;set; }

		[DataMember]
		public virtual string Nome { get;set; }

		[DataMember]
		public virtual int ConsultazioneId { get;set; }

		[DataMember]
		public virtual bool Supervisor { get;set; }

		[DataMember]
		public virtual bool Amministratore { get;set; }

		[DataMember]
		public virtual bool Utente { get;set; }

		[DataMember]
		public virtual ConsultazioneDto Consultazione { get;set; }

		[DataMember]
		public virtual IList<SezioneDto> Seziones { get;set; }

	}
	
}
#pragma warning restore 1591
