#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Affluenza
	{
		private Int _id;
		public virtual Int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private Int _sezioneID;
		public virtual Int SezioneID
		{
			get
			{
				return this._sezioneID;
			}
			set
			{
				this._sezioneID = value;
			}
		}
		
		private DateTime _orario;
		public virtual DateTime Orario
		{
			get
			{
				return this._orario;
			}
			set
			{
				this._orario = value;
			}
		}
		
		private string _stato;
		public virtual string Stato
		{
			get
			{
				return this._stato;
			}
			set
			{
				this._stato = value;
			}
		}
		
		private Int _uomini;
		public virtual Int Uomini
		{
			get
			{
				return this._uomini;
			}
			set
			{
				this._uomini = value;
			}
		}
		
		private Int _donne;
		public virtual Int Donne
		{
			get
			{
				return this._donne;
			}
			set
			{
				this._donne = value;
			}
		}
		
		private Int _totale;
		public virtual Int Totale
		{
			get
			{
				return this._totale;
			}
			set
			{
				this._totale = value;
			}
		}
		
		private Sezione _sezione;
		public virtual Sezione Sezione
		{
			get
			{
				return this._sezione;
			}
			set
			{
				this._sezione = value;
			}
		}
		
	}
}
#pragma warning restore 1591
