#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Collegio
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _consultazioneId;
		public virtual int ConsultazioneId
		{
			get
			{
				return this._consultazioneId;
			}
			set
			{
				this._consultazioneId = value;
			}
		}
		
		private int _numero;
		public virtual int Numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				this._numero = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
		private Consultazione _consultazione;
		public virtual Consultazione Consultazione
		{
			get
			{
				return this._consultazione;
			}
			set
			{
				this._consultazione = value;
			}
		}
		
		private IList<SezioneCollegio> _sezioneCollegios = new List<SezioneCollegio>();
		public virtual IList<SezioneCollegio> SezioneCollegios
		{
			get
			{
				return this._sezioneCollegios;
			}
		}
		
	}
}
#pragma warning restore 1591
