#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Consultazione
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int? _numero;
		public virtual int? Numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				this._numero = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
		private string _tipo;
		public virtual string Tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				this._tipo = value;
			}
		}
		
		private int _comuneId;
		public virtual int ComuneId
		{
			get
			{
				return this._comuneId;
			}
			set
			{
				this._comuneId = value;
			}
		}
		
		private DateTime _dataInizio;
		public virtual DateTime DataInizio
		{
			get
			{
				return this._dataInizio;
			}
			set
			{
				this._dataInizio = value;
			}
		}
		
		private DateTime _dataFine;
		public virtual DateTime DataFine
		{
			get
			{
				return this._dataFine;
			}
			set
			{
				this._dataFine = value;
			}
		}
		
		private Comune _comune;
		public virtual Comune Comune
		{
			get
			{
				return this._comune;
			}
			set
			{
				this._comune = value;
			}
		}
		
		private IList<Collegio> _collegios = new List<Collegio>();
		public virtual IList<Collegio> Collegios
		{
			get
			{
				return this._collegios;
			}
		}
		
		private IList<Affluenza> _affluenzas = new List<Affluenza>();
		public virtual IList<Affluenza> Affluenzas
		{
			get
			{
				return this._affluenzas;
			}
		}
		
		private IList<Scrutinio> _scrutinios = new List<Scrutinio>();
		public virtual IList<Scrutinio> Scrutinios
		{
			get
			{
				return this._scrutinios;
			}
		}
		
		private IList<SedeElettorale> _sedeElettorales = new List<SedeElettorale>();
		public virtual IList<SedeElettorale> SedeElettorales
		{
			get
			{
				return this._sedeElettorales;
			}
		}
		
		private IList<Operatore> _operatores = new List<Operatore>();
		public virtual IList<Operatore> Operatores
		{
			get
			{
				return this._operatores;
			}
		}
		
		private IList<CapoCoalizione> _capoCoaliziones = new List<CapoCoalizione>();
		public virtual IList<CapoCoalizione> CapoCoaliziones
		{
			get
			{
				return this._capoCoaliziones;
			}
		}
		
	}
}
#pragma warning restore 1591
