#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class EAPEntitiesModel : OpenAccessContext, IEAPEntitiesModelUnitOfWork
	{
		private static string connectionStringName = @"Sql755035_3Connection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EAPEntitiesModel.rlinq");
		
		public EAPEntitiesModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public EAPEntitiesModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public EAPEntitiesModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public EAPEntitiesModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public EAPEntitiesModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Soraldo_ele_widget> Soraldo_ele_widgets 
		{
			get
			{
				return this.GetAll<Soraldo_ele_widget>();
			}
		}
		
		public IQueryable<Soraldo_ele_voti_ref> Soraldo_ele_voti_refs 
		{
			get
			{
				return this.GetAll<Soraldo_ele_voti_ref>();
			}
		}
		
		public IQueryable<Soraldo_ele_voti_parziale> Soraldo_ele_voti_parziales 
		{
			get
			{
				return this.GetAll<Soraldo_ele_voti_parziale>();
			}
		}
		
		public IQueryable<Soraldo_ele_voti_listum> Soraldo_ele_voti_lista 
		{
			get
			{
				return this.GetAll<Soraldo_ele_voti_listum>();
			}
		}
		
		public IQueryable<Soraldo_ele_voti_gruppo> Soraldo_ele_voti_gruppos 
		{
			get
			{
				return this.GetAll<Soraldo_ele_voti_gruppo>();
			}
		}
		
		public IQueryable<Soraldo_ele_voti_candidati> Soraldo_ele_voti_candidatis 
		{
			get
			{
				return this.GetAll<Soraldo_ele_voti_candidati>();
			}
		}
		
		public IQueryable<Soraldo_ele_tipo> Soraldo_ele_tipos 
		{
			get
			{
				return this.GetAll<Soraldo_ele_tipo>();
			}
		}
		
		public IQueryable<Soraldo_ele_temi> Soraldo_ele_temis 
		{
			get
			{
				return this.GetAll<Soraldo_ele_temi>();
			}
		}
		
		public IQueryable<Soraldo_ele_sezioni> Soraldo_ele_sezionis 
		{
			get
			{
				return this.GetAll<Soraldo_ele_sezioni>();
			}
		}
		
		public IQueryable<Soraldo_ele_servizi> Soraldo_ele_servizis 
		{
			get
			{
				return this.GetAll<Soraldo_ele_servizi>();
			}
		}
		
		public IQueryable<Soraldo_ele_sede> Soraldo_ele_sedes 
		{
			get
			{
				return this.GetAll<Soraldo_ele_sede>();
			}
		}
		
		public IQueryable<Soraldo_ele_rilaff> Soraldo_ele_rilaffs 
		{
			get
			{
				return this.GetAll<Soraldo_ele_rilaff>();
			}
		}
		
		public IQueryable<Soraldo_ele_regioni> Soraldo_ele_regionis 
		{
			get
			{
				return this.GetAll<Soraldo_ele_regioni>();
			}
		}
		
		public IQueryable<Soraldo_ele_province> Soraldo_ele_provinces 
		{
			get
			{
				return this.GetAll<Soraldo_ele_province>();
			}
		}
		
		public IQueryable<Soraldo_ele_operatori> Soraldo_ele_operatoris 
		{
			get
			{
				return this.GetAll<Soraldo_ele_operatori>();
			}
		}
		
		public IQueryable<Soraldo_ele_numeri> Soraldo_ele_numeris 
		{
			get
			{
				return this.GetAll<Soraldo_ele_numeri>();
			}
		}
		
		public IQueryable<Soraldo_ele_modelli> Soraldo_ele_modellis 
		{
			get
			{
				return this.GetAll<Soraldo_ele_modelli>();
			}
		}
		
		public IQueryable<Soraldo_ele_log> Soraldo_ele_logs 
		{
			get
			{
				return this.GetAll<Soraldo_ele_log>();
			}
		}
		
		public IQueryable<Soraldo_ele_listum> Soraldo_ele_lista 
		{
			get
			{
				return this.GetAll<Soraldo_ele_listum>();
			}
		}
		
		public IQueryable<Soraldo_ele_link> Soraldo_ele_links 
		{
			get
			{
				return this.GetAll<Soraldo_ele_link>();
			}
		}
		
		public IQueryable<Soraldo_ele_gruppo> Soraldo_ele_gruppos 
		{
			get
			{
				return this.GetAll<Soraldo_ele_gruppo>();
			}
		}
		
		public IQueryable<Soraldo_ele_fasce> Soraldo_ele_fasces 
		{
			get
			{
				return this.GetAll<Soraldo_ele_fasce>();
			}
		}
		
		public IQueryable<Soraldo_ele_documenti> Soraldo_ele_documentis 
		{
			get
			{
				return this.GetAll<Soraldo_ele_documenti>();
			}
		}
		
		public IQueryable<Soraldo_ele_consultazione> Soraldo_ele_consultaziones 
		{
			get
			{
				return this.GetAll<Soraldo_ele_consultazione>();
			}
		}
		
		public IQueryable<Soraldo_ele_cons_comune> Soraldo_ele_cons_comunes 
		{
			get
			{
				return this.GetAll<Soraldo_ele_cons_comune>();
			}
		}
		
		public IQueryable<Soraldo_ele_conf> Soraldo_ele_confs 
		{
			get
			{
				return this.GetAll<Soraldo_ele_conf>();
			}
		}
		
		public IQueryable<Soraldo_ele_comuni> Soraldo_ele_comunis 
		{
			get
			{
				return this.GetAll<Soraldo_ele_comuni>();
			}
		}
		
		public IQueryable<Soraldo_ele_comu_collegi> Soraldo_ele_comu_collegis 
		{
			get
			{
				return this.GetAll<Soraldo_ele_comu_collegi>();
			}
		}
		
		public IQueryable<Soraldo_ele_come> Soraldo_ele_comes 
		{
			get
			{
				return this.GetAll<Soraldo_ele_come>();
			}
		}
		
		public IQueryable<Soraldo_ele_collegi_sezioni> Soraldo_ele_collegi_sezionis 
		{
			get
			{
				return this.GetAll<Soraldo_ele_collegi_sezioni>();
			}
		}
		
		public IQueryable<Soraldo_ele_collegi> Soraldo_ele_collegis 
		{
			get
			{
				return this.GetAll<Soraldo_ele_collegi>();
			}
		}
		
		public IQueryable<Soraldo_ele_circoscrizione> Soraldo_ele_circoscriziones 
		{
			get
			{
				return this.GetAll<Soraldo_ele_circoscrizione>();
			}
		}
		
		public IQueryable<Soraldo_ele_candidati> Soraldo_ele_candidatis 
		{
			get
			{
				return this.GetAll<Soraldo_ele_candidati>();
			}
		}
		
		public IQueryable<Soraldo_doc_con> Soraldo_doc_cons 
		{
			get
			{
				return this.GetAll<Soraldo_doc_con>();
			}
		}
		
		public IQueryable<Soraldo_config> Soraldo_configs 
		{
			get
			{
				return this.GetAll<Soraldo_config>();
			}
		}
		
		public IQueryable<Soraldo_author> Soraldo_authors 
		{
			get
			{
				return this.GetAll<Soraldo_author>();
			}
		}
		
		public IQueryable<Soraldo_access> Soraldo_accesses 
		{
			get
			{
				return this.GetAll<Soraldo_access>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of EAPEntitiesModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of EAPEntitiesModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IEAPEntitiesModelUnitOfWork : IUnitOfWork
	{
		IQueryable<Soraldo_ele_widget> Soraldo_ele_widgets
		{
			get;
		}
		IQueryable<Soraldo_ele_voti_ref> Soraldo_ele_voti_refs
		{
			get;
		}
		IQueryable<Soraldo_ele_voti_parziale> Soraldo_ele_voti_parziales
		{
			get;
		}
		IQueryable<Soraldo_ele_voti_listum> Soraldo_ele_voti_lista
		{
			get;
		}
		IQueryable<Soraldo_ele_voti_gruppo> Soraldo_ele_voti_gruppos
		{
			get;
		}
		IQueryable<Soraldo_ele_voti_candidati> Soraldo_ele_voti_candidatis
		{
			get;
		}
		IQueryable<Soraldo_ele_tipo> Soraldo_ele_tipos
		{
			get;
		}
		IQueryable<Soraldo_ele_temi> Soraldo_ele_temis
		{
			get;
		}
		IQueryable<Soraldo_ele_sezioni> Soraldo_ele_sezionis
		{
			get;
		}
		IQueryable<Soraldo_ele_servizi> Soraldo_ele_servizis
		{
			get;
		}
		IQueryable<Soraldo_ele_sede> Soraldo_ele_sedes
		{
			get;
		}
		IQueryable<Soraldo_ele_rilaff> Soraldo_ele_rilaffs
		{
			get;
		}
		IQueryable<Soraldo_ele_regioni> Soraldo_ele_regionis
		{
			get;
		}
		IQueryable<Soraldo_ele_province> Soraldo_ele_provinces
		{
			get;
		}
		IQueryable<Soraldo_ele_operatori> Soraldo_ele_operatoris
		{
			get;
		}
		IQueryable<Soraldo_ele_numeri> Soraldo_ele_numeris
		{
			get;
		}
		IQueryable<Soraldo_ele_modelli> Soraldo_ele_modellis
		{
			get;
		}
		IQueryable<Soraldo_ele_log> Soraldo_ele_logs
		{
			get;
		}
		IQueryable<Soraldo_ele_listum> Soraldo_ele_lista
		{
			get;
		}
		IQueryable<Soraldo_ele_link> Soraldo_ele_links
		{
			get;
		}
		IQueryable<Soraldo_ele_gruppo> Soraldo_ele_gruppos
		{
			get;
		}
		IQueryable<Soraldo_ele_fasce> Soraldo_ele_fasces
		{
			get;
		}
		IQueryable<Soraldo_ele_documenti> Soraldo_ele_documentis
		{
			get;
		}
		IQueryable<Soraldo_ele_consultazione> Soraldo_ele_consultaziones
		{
			get;
		}
		IQueryable<Soraldo_ele_cons_comune> Soraldo_ele_cons_comunes
		{
			get;
		}
		IQueryable<Soraldo_ele_conf> Soraldo_ele_confs
		{
			get;
		}
		IQueryable<Soraldo_ele_comuni> Soraldo_ele_comunis
		{
			get;
		}
		IQueryable<Soraldo_ele_comu_collegi> Soraldo_ele_comu_collegis
		{
			get;
		}
		IQueryable<Soraldo_ele_come> Soraldo_ele_comes
		{
			get;
		}
		IQueryable<Soraldo_ele_collegi_sezioni> Soraldo_ele_collegi_sezionis
		{
			get;
		}
		IQueryable<Soraldo_ele_collegi> Soraldo_ele_collegis
		{
			get;
		}
		IQueryable<Soraldo_ele_circoscrizione> Soraldo_ele_circoscriziones
		{
			get;
		}
		IQueryable<Soraldo_ele_candidati> Soraldo_ele_candidatis
		{
			get;
		}
		IQueryable<Soraldo_doc_con> Soraldo_doc_cons
		{
			get;
		}
		IQueryable<Soraldo_config> Soraldo_configs
		{
			get;
		}
		IQueryable<Soraldo_author> Soraldo_authors
		{
			get;
		}
		IQueryable<Soraldo_access> Soraldo_accesses
		{
			get;
		}
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_widget
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _nome_file;
		public virtual string Nome_file
		{
			get
			{
				return this._nome_file;
			}
			set
			{
				this._nome_file = value;
			}
		}
		
		private string _titolo;
		public virtual string Titolo
		{
			get
			{
				return this._titolo;
			}
			set
			{
				this._titolo = value;
			}
		}
		
		private int _pos_or;
		public virtual int Pos_or
		{
			get
			{
				return this._pos_or;
			}
			set
			{
				this._pos_or = value;
			}
		}
		
		private int _pos_ver;
		public virtual int Pos_ver
		{
			get
			{
				return this._pos_ver;
			}
			set
			{
				this._pos_ver = value;
			}
		}
		
		private int _attivo;
		public virtual int Attivo
		{
			get
			{
				return this._attivo;
			}
			set
			{
				this._attivo = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_voti_ref
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _id_gruppo;
		public virtual int Id_gruppo
		{
			get
			{
				return this._id_gruppo;
			}
			set
			{
				this._id_gruppo = value;
			}
		}
		
		private int _id_sez;
		public virtual int Id_sez
		{
			get
			{
				return this._id_sez;
			}
			set
			{
				this._id_sez = value;
			}
		}
		
		private int? _si;
		public virtual int? Si
		{
			get
			{
				return this._si;
			}
			set
			{
				this._si = value;
			}
		}
		
		private int? _no;
		public virtual int? No
		{
			get
			{
				return this._no;
			}
			set
			{
				this._no = value;
			}
		}
		
		private int? _validi;
		public virtual int? Validi
		{
			get
			{
				return this._validi;
			}
			set
			{
				this._validi = value;
			}
		}
		
		private int? _nulli;
		public virtual int? Nulli
		{
			get
			{
				return this._nulli;
			}
			set
			{
				this._nulli = value;
			}
		}
		
		private int? _bianchi;
		public virtual int? Bianchi
		{
			get
			{
				return this._bianchi;
			}
			set
			{
				this._bianchi = value;
			}
		}
		
		private int? _contestati;
		public virtual int? Contestati
		{
			get
			{
				return this._contestati;
			}
			set
			{
				this._contestati = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_voti_parziale
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _id_sez;
		public virtual int Id_sez
		{
			get
			{
				return this._id_sez;
			}
			set
			{
				this._id_sez = value;
			}
		}
		
		private int _id_parz;
		public virtual int Id_parz
		{
			get
			{
				return this._id_parz;
			}
			set
			{
				this._id_parz = value;
			}
		}
		
		private DateTime _orario;
		public virtual DateTime Orario
		{
			get
			{
				return this._orario;
			}
			set
			{
				this._orario = value;
			}
		}
		
		private DateTime _data;
		public virtual DateTime Data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
		
		private int _voti_uomini;
		public virtual int Voti_uomini
		{
			get
			{
				return this._voti_uomini;
			}
			set
			{
				this._voti_uomini = value;
			}
		}
		
		private int _voti_donne;
		public virtual int Voti_donne
		{
			get
			{
				return this._voti_donne;
			}
			set
			{
				this._voti_donne = value;
			}
		}
		
		private int _voti_complessivi;
		public virtual int Voti_complessivi
		{
			get
			{
				return this._voti_complessivi;
			}
			set
			{
				this._voti_complessivi = value;
			}
		}
		
		private int _id_gruppo;
		public virtual int Id_gruppo
		{
			get
			{
				return this._id_gruppo;
			}
			set
			{
				this._id_gruppo = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_voti_listum
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _id_lista;
		public virtual int Id_lista
		{
			get
			{
				return this._id_lista;
			}
			set
			{
				this._id_lista = value;
			}
		}
		
		private int _id_sez;
		public virtual int Id_sez
		{
			get
			{
				return this._id_sez;
			}
			set
			{
				this._id_sez = value;
			}
		}
		
		private int _voti;
		public virtual int Voti
		{
			get
			{
				return this._voti;
			}
			set
			{
				this._voti = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_voti_gruppo
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _id_gruppo;
		public virtual int Id_gruppo
		{
			get
			{
				return this._id_gruppo;
			}
			set
			{
				this._id_gruppo = value;
			}
		}
		
		private int _id_sez;
		public virtual int Id_sez
		{
			get
			{
				return this._id_sez;
			}
			set
			{
				this._id_sez = value;
			}
		}
		
		private int _voti;
		public virtual int Voti
		{
			get
			{
				return this._voti;
			}
			set
			{
				this._voti = value;
			}
		}
		
		private uint _lista;
		public virtual uint Lista
		{
			get
			{
				return this._lista;
			}
			set
			{
				this._lista = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_voti_candidati
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _id_cand;
		public virtual int Id_cand
		{
			get
			{
				return this._id_cand;
			}
			set
			{
				this._id_cand = value;
			}
		}
		
		private int _id_sez;
		public virtual int Id_sez
		{
			get
			{
				return this._id_sez;
			}
			set
			{
				this._id_sez = value;
			}
		}
		
		private int _voti;
		public virtual int Voti
		{
			get
			{
				return this._voti;
			}
			set
			{
				this._voti = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_tipo
	{
		private int _tipo_cons;
		public virtual int Tipo_cons
		{
			get
			{
				return this._tipo_cons;
			}
			set
			{
				this._tipo_cons = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
		private string _lingua;
		public virtual string Lingua
		{
			get
			{
				return this._lingua;
			}
			set
			{
				this._lingua = value;
			}
		}
		
		private short _genere;
		public virtual short Genere
		{
			get
			{
				return this._genere;
			}
			set
			{
				this._genere = value;
			}
		}
		
		private string _voto_g;
		public virtual string Voto_g
		{
			get
			{
				return this._voto_g;
			}
			set
			{
				this._voto_g = value;
			}
		}
		
		private string _voto_l;
		public virtual string Voto_l
		{
			get
			{
				return this._voto_l;
			}
			set
			{
				this._voto_l = value;
			}
		}
		
		private string _voto_c;
		public virtual string Voto_c
		{
			get
			{
				return this._voto_c;
			}
			set
			{
				this._voto_c = value;
			}
		}
		
		private string _circo;
		public virtual string Circo
		{
			get
			{
				return this._circo;
			}
			set
			{
				this._circo = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_temi
	{
		private string _tema;
		public virtual string Tema
		{
			get
			{
				return this._tema;
			}
			set
			{
				this._tema = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_sezioni
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _id_sez;
		public virtual int Id_sez
		{
			get
			{
				return this._id_sez;
			}
			set
			{
				this._id_sez = value;
			}
		}
		
		private int _id_sede;
		public virtual int Id_sede
		{
			get
			{
				return this._id_sede;
			}
			set
			{
				this._id_sede = value;
			}
		}
		
		private int _num_sez;
		public virtual int Num_sez
		{
			get
			{
				return this._num_sez;
			}
			set
			{
				this._num_sez = value;
			}
		}
		
		private int? _maschi;
		public virtual int? Maschi
		{
			get
			{
				return this._maschi;
			}
			set
			{
				this._maschi = value;
			}
		}
		
		private int? _femmine;
		public virtual int? Femmine
		{
			get
			{
				return this._femmine;
			}
			set
			{
				this._femmine = value;
			}
		}
		
		private int _validi;
		public virtual int Validi
		{
			get
			{
				return this._validi;
			}
			set
			{
				this._validi = value;
			}
		}
		
		private int _nulli;
		public virtual int Nulli
		{
			get
			{
				return this._nulli;
			}
			set
			{
				this._nulli = value;
			}
		}
		
		private int _bianchi;
		public virtual int Bianchi
		{
			get
			{
				return this._bianchi;
			}
			set
			{
				this._bianchi = value;
			}
		}
		
		private int _contestati;
		public virtual int Contestati
		{
			get
			{
				return this._contestati;
			}
			set
			{
				this._contestati = value;
			}
		}
		
		private int _solo_gruppo;
		public virtual int Solo_gruppo
		{
			get
			{
				return this._solo_gruppo;
			}
			set
			{
				this._solo_gruppo = value;
			}
		}
		
		private int _autorizzati_m;
		public virtual int Autorizzati_m
		{
			get
			{
				return this._autorizzati_m;
			}
			set
			{
				this._autorizzati_m = value;
			}
		}
		
		private int _autorizzati_f;
		public virtual int Autorizzati_f
		{
			get
			{
				return this._autorizzati_f;
			}
			set
			{
				this._autorizzati_f = value;
			}
		}
		
		private int _voti_nulli;
		public virtual int Voti_nulli
		{
			get
			{
				return this._voti_nulli;
			}
			set
			{
				this._voti_nulli = value;
			}
		}
		
		private int _validi_lista;
		public virtual int Validi_lista
		{
			get
			{
				return this._validi_lista;
			}
			set
			{
				this._validi_lista = value;
			}
		}
		
		private int _contestati_lista;
		public virtual int Contestati_lista
		{
			get
			{
				return this._contestati_lista;
			}
			set
			{
				this._contestati_lista = value;
			}
		}
		
		private int _voti_nulli_lista;
		public virtual int Voti_nulli_lista
		{
			get
			{
				return this._voti_nulli_lista;
			}
			set
			{
				this._voti_nulli_lista = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_servizi
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _mid;
		public virtual int Mid
		{
			get
			{
				return this._mid;
			}
			set
			{
				this._mid = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private string _preamble;
		public virtual string Preamble
		{
			get
			{
				return this._preamble;
			}
			set
			{
				this._preamble = value;
			}
		}
		
		private string _content;
		public virtual string Content
		{
			get
			{
				return this._content;
			}
			set
			{
				this._content = value;
			}
		}
		
		private string _editimage;
		public virtual string Editimage
		{
			get
			{
				return this._editimage;
			}
			set
			{
				this._editimage = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_sede
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _id_sede;
		public virtual int Id_sede
		{
			get
			{
				return this._id_sede;
			}
			set
			{
				this._id_sede = value;
			}
		}
		
		private int _id_circ;
		public virtual int Id_circ
		{
			get
			{
				return this._id_circ;
			}
			set
			{
				this._id_circ = value;
			}
		}
		
		private string _indirizzo;
		public virtual string Indirizzo
		{
			get
			{
				return this._indirizzo;
			}
			set
			{
				this._indirizzo = value;
			}
		}
		
		private string _telefono1;
		public virtual string Telefono1
		{
			get
			{
				return this._telefono1;
			}
			set
			{
				this._telefono1 = value;
			}
		}
		
		private string _telefono2;
		public virtual string Telefono2
		{
			get
			{
				return this._telefono2;
			}
			set
			{
				this._telefono2 = value;
			}
		}
		
		private string _fax;
		public virtual string Fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				this._fax = value;
			}
		}
		
		private string _responsabile;
		public virtual string Responsabile
		{
			get
			{
				return this._responsabile;
			}
			set
			{
				this._responsabile = value;
			}
		}
		
		private byte[] _mappa;
		public virtual byte[] Mappa
		{
			get
			{
				return this._mappa;
			}
			set
			{
				this._mappa = value;
			}
		}
		
		private string _filemappa;
		public virtual string Filemappa
		{
			get
			{
				return this._filemappa;
			}
			set
			{
				this._filemappa = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_rilaff
	{
		private int _id_cons_gen;
		public virtual int Id_cons_gen
		{
			get
			{
				return this._id_cons_gen;
			}
			set
			{
				this._id_cons_gen = value;
			}
		}
		
		private DateTime _orario;
		public virtual DateTime Orario
		{
			get
			{
				return this._orario;
			}
			set
			{
				this._orario = value;
			}
		}
		
		private DateTime _data;
		public virtual DateTime Data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_regioni
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_province
	{
		private short _id;
		public virtual short Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_operatori
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _id_sede;
		public virtual int Id_sede
		{
			get
			{
				return this._id_sede;
			}
			set
			{
				this._id_sede = value;
			}
		}
		
		private int _id_comune;
		public virtual int Id_comune
		{
			get
			{
				return this._id_comune;
			}
			set
			{
				this._id_comune = value;
			}
		}
		
		private int? _permessi;
		public virtual int? Permessi
		{
			get
			{
				return this._permessi;
			}
			set
			{
				this._permessi = value;
			}
		}
		
		private string _aid;
		public virtual string Aid
		{
			get
			{
				return this._aid;
			}
			set
			{
				this._aid = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_numeri
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _mid;
		public virtual int Mid
		{
			get
			{
				return this._mid;
			}
			set
			{
				this._mid = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private string _preamble;
		public virtual string Preamble
		{
			get
			{
				return this._preamble;
			}
			set
			{
				this._preamble = value;
			}
		}
		
		private string _content;
		public virtual string Content
		{
			get
			{
				return this._content;
			}
			set
			{
				this._content = value;
			}
		}
		
		private string _editimage;
		public virtual string Editimage
		{
			get
			{
				return this._editimage;
			}
			set
			{
				this._editimage = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_modelli
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private string _categoria;
		public virtual string Categoria
		{
			get
			{
				return this._categoria;
			}
			set
			{
				this._categoria = value;
			}
		}
		
		private byte[] _modello;
		public virtual byte[] Modello
		{
			get
			{
				return this._modello;
			}
			set
			{
				this._modello = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_log
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _id_sez;
		public virtual int Id_sez
		{
			get
			{
				return this._id_sez;
			}
			set
			{
				this._id_sez = value;
			}
		}
		
		private string _utente;
		public virtual string Utente
		{
			get
			{
				return this._utente;
			}
			set
			{
				this._utente = value;
			}
		}
		
		private DateTime? _data;
		public virtual DateTime? Data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
		
		private DateTime? _ora;
		public virtual DateTime? Ora
		{
			get
			{
				return this._ora;
			}
			set
			{
				this._ora = value;
			}
		}
		
		private string _log_da;
		public virtual string Log_da
		{
			get
			{
				return this._log_da;
			}
			set
			{
				this._log_da = value;
			}
		}
		
		private string _log_a;
		public virtual string Log_a
		{
			get
			{
				return this._log_a;
			}
			set
			{
				this._log_a = value;
			}
		}
		
		private string _tabella;
		public virtual string Tabella
		{
			get
			{
				return this._tabella;
			}
			set
			{
				this._tabella = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_listum
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _id_lista;
		public virtual int Id_lista
		{
			get
			{
				return this._id_lista;
			}
			set
			{
				this._id_lista = value;
			}
		}
		
		private int _num_lista;
		public virtual int Num_lista
		{
			get
			{
				return this._num_lista;
			}
			set
			{
				this._num_lista = value;
			}
		}
		
		private int _id_gruppo;
		public virtual int Id_gruppo
		{
			get
			{
				return this._id_gruppo;
			}
			set
			{
				this._id_gruppo = value;
			}
		}
		
		private int _id_circ;
		public virtual int Id_circ
		{
			get
			{
				return this._id_circ;
			}
			set
			{
				this._id_circ = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
		private string _simbolo;
		public virtual string Simbolo
		{
			get
			{
				return this._simbolo;
			}
			set
			{
				this._simbolo = value;
			}
		}
		
		private byte[] _stemma;
		public virtual byte[] Stemma
		{
			get
			{
				return this._stemma;
			}
			set
			{
				this._stemma = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_link
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _mid;
		public virtual int Mid
		{
			get
			{
				return this._mid;
			}
			set
			{
				this._mid = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private string _preamble;
		public virtual string Preamble
		{
			get
			{
				return this._preamble;
			}
			set
			{
				this._preamble = value;
			}
		}
		
		private string _content;
		public virtual string Content
		{
			get
			{
				return this._content;
			}
			set
			{
				this._content = value;
			}
		}
		
		private string _editimage;
		public virtual string Editimage
		{
			get
			{
				return this._editimage;
			}
			set
			{
				this._editimage = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_gruppo
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _id_gruppo;
		public virtual int Id_gruppo
		{
			get
			{
				return this._id_gruppo;
			}
			set
			{
				this._id_gruppo = value;
			}
		}
		
		private int _num_gruppo;
		public virtual int Num_gruppo
		{
			get
			{
				return this._num_gruppo;
			}
			set
			{
				this._num_gruppo = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
		private string _simbolo;
		public virtual string Simbolo
		{
			get
			{
				return this._simbolo;
			}
			set
			{
				this._simbolo = value;
			}
		}
		
		private byte[] _stemma;
		public virtual byte[] Stemma
		{
			get
			{
				return this._stemma;
			}
			set
			{
				this._stemma = value;
			}
		}
		
		private int _id_circ;
		public virtual int Id_circ
		{
			get
			{
				return this._id_circ;
			}
			set
			{
				this._id_circ = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_fasce
	{
		private int _id_fascia;
		public virtual int Id_fascia
		{
			get
			{
				return this._id_fascia;
			}
			set
			{
				this._id_fascia = value;
			}
		}
		
		private int _abitanti;
		public virtual int Abitanti
		{
			get
			{
				return this._abitanti;
			}
			set
			{
				this._abitanti = value;
			}
		}
		
		private DateTime _data_inizio;
		public virtual DateTime Data_inizio
		{
			get
			{
				return this._data_inizio;
			}
			set
			{
				this._data_inizio = value;
			}
		}
		
		private DateTime _data_fine;
		public virtual DateTime Data_fine
		{
			get
			{
				return this._data_fine;
			}
			set
			{
				this._data_fine = value;
			}
		}
		
		private int _seggi;
		public virtual int Seggi
		{
			get
			{
				return this._seggi;
			}
			set
			{
				this._seggi = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_documenti
	{
		private int _id_doc;
		public virtual int Id_doc
		{
			get
			{
				return this._id_doc;
			}
			set
			{
				this._id_doc = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
		private string _nomedoc;
		public virtual string Nomedoc
		{
			get
			{
				return this._nomedoc;
			}
			set
			{
				this._nomedoc = value;
			}
		}
		
		private byte[] _filedoc;
		public virtual byte[] Filedoc
		{
			get
			{
				return this._filedoc;
			}
			set
			{
				this._filedoc = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_consultazione
	{
		private int _id_cons_gen;
		public virtual int Id_cons_gen
		{
			get
			{
				return this._id_cons_gen;
			}
			set
			{
				this._id_cons_gen = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
		private DateTime? _data_inizio;
		public virtual DateTime? Data_inizio
		{
			get
			{
				return this._data_inizio;
			}
			set
			{
				this._data_inizio = value;
			}
		}
		
		private DateTime? _data_fine;
		public virtual DateTime? Data_fine
		{
			get
			{
				return this._data_fine;
			}
			set
			{
				this._data_fine = value;
			}
		}
		
		private int _tipo_cons;
		public virtual int Tipo_cons
		{
			get
			{
				return this._tipo_cons;
			}
			set
			{
				this._tipo_cons = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_cons_comune
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private string _chiusa;
		public virtual string Chiusa
		{
			get
			{
				return this._chiusa;
			}
			set
			{
				this._chiusa = value;
			}
		}
		
		private int _id_comune;
		public virtual int Id_comune
		{
			get
			{
				return this._id_comune;
			}
			set
			{
				this._id_comune = value;
			}
		}
		
		private int _id_cons_gen;
		public virtual int Id_cons_gen
		{
			get
			{
				return this._id_cons_gen;
			}
			set
			{
				this._id_cons_gen = value;
			}
		}
		
		private int _id_conf;
		public virtual int Id_conf
		{
			get
			{
				return this._id_conf;
			}
			set
			{
				this._id_conf = value;
			}
		}
		
		private string _preferita;
		public virtual string Preferita
		{
			get
			{
				return this._preferita;
			}
			set
			{
				this._preferita = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_conf
	{
		private int _id_conf;
		public virtual int Id_conf
		{
			get
			{
				return this._id_conf;
			}
			set
			{
				this._id_conf = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
		private int _limite;
		public virtual int Limite
		{
			get
			{
				return this._limite;
			}
			set
			{
				this._limite = value;
			}
		}
		
		private string _consin;
		public virtual string Consin
		{
			get
			{
				return this._consin;
			}
			set
			{
				this._consin = value;
			}
		}
		
		private int _infpremio;
		public virtual int Infpremio
		{
			get
			{
				return this._infpremio;
			}
			set
			{
				this._infpremio = value;
			}
		}
		
		private int _supsbarramento;
		public virtual int Supsbarramento
		{
			get
			{
				return this._supsbarramento;
			}
			set
			{
				this._supsbarramento = value;
			}
		}
		
		private int _suppremio;
		public virtual int Suppremio
		{
			get
			{
				return this._suppremio;
			}
			set
			{
				this._suppremio = value;
			}
		}
		
		private int _listinfsbar;
		public virtual int Listinfsbar
		{
			get
			{
				return this._listinfsbar;
			}
			set
			{
				this._listinfsbar = value;
			}
		}
		
		private string _listinfconta;
		public virtual string Listinfconta
		{
			get
			{
				return this._listinfconta;
			}
			set
			{
				this._listinfconta = value;
			}
		}
		
		private string _listsupconta;
		public virtual string Listsupconta
		{
			get
			{
				return this._listsupconta;
			}
			set
			{
				this._listsupconta = value;
			}
		}
		
		private int _supminpremio;
		public virtual int Supminpremio
		{
			get
			{
				return this._supminpremio;
			}
			set
			{
				this._supminpremio = value;
			}
		}
		
		private int _infminpremio;
		public virtual int Infminpremio
		{
			get
			{
				return this._infminpremio;
			}
			set
			{
				this._infminpremio = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_comuni
	{
		private int _id_comune;
		public virtual int Id_comune
		{
			get
			{
				return this._id_comune;
			}
			set
			{
				this._id_comune = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
		private string _indirizzo;
		public virtual string Indirizzo
		{
			get
			{
				return this._indirizzo;
			}
			set
			{
				this._indirizzo = value;
			}
		}
		
		private string _centralino;
		public virtual string Centralino
		{
			get
			{
				return this._centralino;
			}
			set
			{
				this._centralino = value;
			}
		}
		
		private string _fax;
		public virtual string Fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				this._fax = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private short _fascia;
		public virtual short Fascia
		{
			get
			{
				return this._fascia;
			}
			set
			{
				this._fascia = value;
			}
		}
		
		private string _capoluogo;
		public virtual string Capoluogo
		{
			get
			{
				return this._capoluogo;
			}
			set
			{
				this._capoluogo = value;
			}
		}
		
		private string _simbolo;
		public virtual string Simbolo
		{
			get
			{
				return this._simbolo;
			}
			set
			{
				this._simbolo = value;
			}
		}
		
		private byte[] _stemma;
		public virtual byte[] Stemma
		{
			get
			{
				return this._stemma;
			}
			set
			{
				this._stemma = value;
			}
		}
		
		private int? _id_cons;
		public virtual int? Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_comu_collegi
	{
		private int _id_collegio;
		public virtual int Id_collegio
		{
			get
			{
				return this._id_collegio;
			}
			set
			{
				this._id_collegio = value;
			}
		}
		
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _id_comune;
		public virtual int Id_comune
		{
			get
			{
				return this._id_comune;
			}
			set
			{
				this._id_comune = value;
			}
		}
		
		private int _id_cons_gen;
		public virtual int Id_cons_gen
		{
			get
			{
				return this._id_cons_gen;
			}
			set
			{
				this._id_cons_gen = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_come
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _mid;
		public virtual int Mid
		{
			get
			{
				return this._mid;
			}
			set
			{
				this._mid = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private string _preamble;
		public virtual string Preamble
		{
			get
			{
				return this._preamble;
			}
			set
			{
				this._preamble = value;
			}
		}
		
		private string _content;
		public virtual string Content
		{
			get
			{
				return this._content;
			}
			set
			{
				this._content = value;
			}
		}
		
		private string _editimage;
		public virtual string Editimage
		{
			get
			{
				return this._editimage;
			}
			set
			{
				this._editimage = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_collegi_sezioni
	{
		private int? _id_cons;
		public virtual int? Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _id_collegio;
		public virtual int Id_collegio
		{
			get
			{
				return this._id_collegio;
			}
			set
			{
				this._id_collegio = value;
			}
		}
		
		private int _id_sez;
		public virtual int Id_sez
		{
			get
			{
				return this._id_sez;
			}
			set
			{
				this._id_sez = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_collegi
	{
		private int _id_collegio;
		public virtual int Id_collegio
		{
			get
			{
				return this._id_collegio;
			}
			set
			{
				this._id_collegio = value;
			}
		}
		
		private int _id_cons_gen;
		public virtual int Id_cons_gen
		{
			get
			{
				return this._id_cons_gen;
			}
			set
			{
				this._id_cons_gen = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_circoscrizione
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _id_circ;
		public virtual int Id_circ
		{
			get
			{
				return this._id_circ;
			}
			set
			{
				this._id_circ = value;
			}
		}
		
		private int _num_circ;
		public virtual int Num_circ
		{
			get
			{
				return this._num_circ;
			}
			set
			{
				this._num_circ = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_ele_candidati
	{
		private int _id_cand;
		public virtual int Id_cand
		{
			get
			{
				return this._id_cand;
			}
			set
			{
				this._id_cand = value;
			}
		}
		
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _id_lista;
		public virtual int Id_lista
		{
			get
			{
				return this._id_lista;
			}
			set
			{
				this._id_lista = value;
			}
		}
		
		private string _cognome;
		public virtual string Cognome
		{
			get
			{
				return this._cognome;
			}
			set
			{
				this._cognome = value;
			}
		}
		
		private string _nome;
		public virtual string Nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		
		private string _note;
		public virtual string Note
		{
			get
			{
				return this._note;
			}
			set
			{
				this._note = value;
			}
		}
		
		private string _simbolo;
		public virtual string Simbolo
		{
			get
			{
				return this._simbolo;
			}
			set
			{
				this._simbolo = value;
			}
		}
		
		private int _num_cand;
		public virtual int Num_cand
		{
			get
			{
				return this._num_cand;
			}
			set
			{
				this._num_cand = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_doc_con
	{
		private int _id_cons;
		public virtual int Id_cons
		{
			get
			{
				return this._id_cons;
			}
			set
			{
				this._id_cons = value;
			}
		}
		
		private int _id_doc;
		public virtual int Id_doc
		{
			get
			{
				return this._id_doc;
			}
			set
			{
				this._id_doc = value;
			}
		}
		
		private string _tabella;
		public virtual string Tabella
		{
			get
			{
				return this._tabella;
			}
			set
			{
				this._tabella = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_config
	{
		private string _sitename;
		public virtual string Sitename
		{
			get
			{
				return this._sitename;
			}
			set
			{
				this._sitename = value;
			}
		}
		
		private string _siteurl;
		public virtual string Siteurl
		{
			get
			{
				return this._siteurl;
			}
			set
			{
				this._siteurl = value;
			}
		}
		
		private string _site_logo;
		public virtual string Site_logo
		{
			get
			{
				return this._site_logo;
			}
			set
			{
				this._site_logo = value;
			}
		}
		
		private string _slogan;
		public virtual string Slogan
		{
			get
			{
				return this._slogan;
			}
			set
			{
				this._slogan = value;
			}
		}
		
		private string _startdate;
		public virtual string Startdate
		{
			get
			{
				return this._startdate;
			}
			set
			{
				this._startdate = value;
			}
		}
		
		private string _adminmail;
		public virtual string Adminmail
		{
			get
			{
				return this._adminmail;
			}
			set
			{
				this._adminmail = value;
			}
		}
		
		private string _tema;
		public virtual string Tema
		{
			get
			{
				return this._tema;
			}
			set
			{
				this._tema = value;
			}
		}
		
		private string _foot;
		public virtual string Foot
		{
			get
			{
				return this._foot;
			}
			set
			{
				this._foot = value;
			}
		}
		
		private string _language;
		public virtual string Language
		{
			get
			{
				return this._language;
			}
			set
			{
				this._language = value;
			}
		}
		
		private string _blocco;
		public virtual string Blocco
		{
			get
			{
				return this._blocco;
			}
			set
			{
				this._blocco = value;
			}
		}
		
		private byte[] _testata;
		public virtual byte[] Testata
		{
			get
			{
				return this._testata;
			}
			set
			{
				this._testata = value;
			}
		}
		
		private string _nome_testata;
		public virtual string Nome_testata
		{
			get
			{
				return this._nome_testata;
			}
			set
			{
				this._nome_testata = value;
			}
		}
		
		private string _fileout;
		public virtual string Fileout
		{
			get
			{
				return this._fileout;
			}
			set
			{
				this._fileout = value;
			}
		}
		
		private string _copyright;
		public virtual string Copyright
		{
			get
			{
				return this._copyright;
			}
			set
			{
				this._copyright = value;
			}
		}
		
		private int _versione;
		public virtual int Versione
		{
			get
			{
				return this._versione;
			}
			set
			{
				this._versione = value;
			}
		}
		
		private int _patch;
		public virtual int Patch
		{
			get
			{
				return this._patch;
			}
			set
			{
				this._patch = value;
			}
		}
		
		private int _siteistat;
		public virtual int Siteistat
		{
			get
			{
				return this._siteistat;
			}
			set
			{
				this._siteistat = value;
			}
		}
		
		private string _multicomune;
		public virtual string Multicomune
		{
			get
			{
				return this._multicomune;
			}
			set
			{
				this._multicomune = value;
			}
		}
		
		private string _flash;
		public virtual string Flash
		{
			get
			{
				return this._flash;
			}
			set
			{
				this._flash = value;
			}
		}
		
		private string _displayerrors;
		public virtual string Displayerrors
		{
			get
			{
				return this._displayerrors;
			}
			set
			{
				this._displayerrors = value;
			}
		}
		
		private string _gkey;
		public virtual string Gkey
		{
			get
			{
				return this._gkey;
			}
			set
			{
				this._gkey = value;
			}
		}
		
		private string _googlemaps;
		public virtual string Googlemaps
		{
			get
			{
				return this._googlemaps;
			}
			set
			{
				this._googlemaps = value;
			}
		}
		
		private string _editor;
		public virtual string Editor
		{
			get
			{
				return this._editor;
			}
			set
			{
				this._editor = value;
			}
		}
		
		private string _tema_on;
		public virtual string Tema_on
		{
			get
			{
				return this._tema_on;
			}
			set
			{
				this._tema_on = value;
			}
		}
		
		private string _ed_user;
		public virtual string Ed_user
		{
			get
			{
				return this._ed_user;
			}
			set
			{
				this._ed_user = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_author
	{
		private string _aid;
		public virtual string Aid
		{
			get
			{
				return this._aid;
			}
			set
			{
				this._aid = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private int _id_comune;
		public virtual int Id_comune
		{
			get
			{
				return this._id_comune;
			}
			set
			{
				this._id_comune = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private string _pwd;
		public virtual string Pwd
		{
			get
			{
				return this._pwd;
			}
			set
			{
				this._pwd = value;
			}
		}
		
		private int _counter;
		public virtual int Counter
		{
			get
			{
				return this._counter;
			}
			set
			{
				this._counter = value;
			}
		}
		
		private short _adminop;
		public virtual short Adminop
		{
			get
			{
				return this._adminop;
			}
			set
			{
				this._adminop = value;
			}
		}
		
		private short _admincomune;
		public virtual short Admincomune
		{
			get
			{
				return this._admincomune;
			}
			set
			{
				this._admincomune = value;
			}
		}
		
		private short _adminsuper;
		public virtual short Adminsuper
		{
			get
			{
				return this._adminsuper;
			}
			set
			{
				this._adminsuper = value;
			}
		}
		
		private string _admlanguage;
		public virtual string Admlanguage
		{
			get
			{
				return this._admlanguage;
			}
			set
			{
				this._admlanguage = value;
			}
		}
		
	}
}
namespace DataLayer	
{
	public partial class Soraldo_access
	{
		private int _access_id;
		public virtual int Access_id
		{
			get
			{
				return this._access_id;
			}
			set
			{
				this._access_id = value;
			}
		}
		
		private string _access_title;
		public virtual string Access_title
		{
			get
			{
				return this._access_title;
			}
			set
			{
				this._access_title = value;
			}
		}
		
	}
}
#pragma warning restore 1591
