#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Lista
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _capoCoalizioneId;
		public virtual int CapoCoalizioneId
		{
			get
			{
				return this._capoCoalizioneId;
			}
			set
			{
				this._capoCoalizioneId = value;
			}
		}
		
		private int? _numero;
		public virtual int? Numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				this._numero = value;
			}
		}
		
		private string _descrizione;
		public virtual string Descrizione
		{
			get
			{
				return this._descrizione;
			}
			set
			{
				this._descrizione = value;
			}
		}
		
		private string _simbolo;
		public virtual string Simbolo
		{
			get
			{
				return this._simbolo;
			}
			set
			{
				this._simbolo = value;
			}
		}
		
		private CapoCoalizione _capoCoalizione;
		public virtual CapoCoalizione CapoCoalizione
		{
			get
			{
				return this._capoCoalizione;
			}
			set
			{
				this._capoCoalizione = value;
			}
		}
		
		private IList<Candidato> _candidatos = new List<Candidato>();
		public virtual IList<Candidato> Candidatos
		{
			get
			{
				return this._candidatos;
			}
		}
		
		private IList<ScrutinioLista> _scrutinioListas = new List<ScrutinioLista>();
		public virtual IList<ScrutinioLista> ScrutinioListas
		{
			get
			{
				return this._scrutinioListas;
			}
		}
		
	}
}
#pragma warning restore 1591
