#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Operatore
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _username;
		public virtual string Username
		{
			get
			{
				return this._username;
			}
			set
			{
				this._username = value;
			}
		}
		
		private string _password;
		public virtual string Password
		{
			get
			{
				return this._password;
			}
			set
			{
				this._password = value;
			}
		}
		
		private string _confermaPassword;
		public virtual string ConfermaPassword
		{
			get
			{
				return this._confermaPassword;
			}
			set
			{
				this._confermaPassword = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private string _telefono;
		public virtual string Telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				this._telefono = value;
			}
		}
		
		private string _cognome;
		public virtual string Cognome
		{
			get
			{
				return this._cognome;
			}
			set
			{
				this._cognome = value;
			}
		}
		
		private string _nome;
		public virtual string Nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		
		private int _consultazioneId;
		public virtual int ConsultazioneId
		{
			get
			{
				return this._consultazioneId;
			}
			set
			{
				this._consultazioneId = value;
			}
		}
		
		private bool _supervisor;
		public virtual bool Supervisor
		{
			get
			{
				return this._supervisor;
			}
			set
			{
				this._supervisor = value;
			}
		}
		
		private bool _amministratore;
		public virtual bool Amministratore
		{
			get
			{
				return this._amministratore;
			}
			set
			{
				this._amministratore = value;
			}
		}
		
		private bool _utente;
		public virtual bool Utente
		{
			get
			{
				return this._utente;
			}
			set
			{
				this._utente = value;
			}
		}
		
		private Consultazione _consultazione;
		public virtual Consultazione Consultazione
		{
			get
			{
				return this._consultazione;
			}
			set
			{
				this._consultazione = value;
			}
		}
		
		private IList<Sezione> _seziones = new List<Sezione>();
		public virtual IList<Sezione> Seziones
		{
			get
			{
				return this._seziones;
			}
		}
		
	}
}
#pragma warning restore 1591
