#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Rilevamento
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int? _uomini;
		public virtual int? Uomini
		{
			get
			{
				return this._uomini;
			}
			set
			{
				this._uomini = value;
			}
		}
		
		private int? _donne;
		public virtual int? Donne
		{
			get
			{
				return this._donne;
			}
			set
			{
				this._donne = value;
			}
		}
		
		private int? _totale;
		public virtual int? Totale
		{
			get
			{
				return this._totale;
			}
			set
			{
				this._totale = value;
			}
		}
		
		private int _affluenzaId;
		public virtual int AffluenzaId
		{
			get
			{
				return this._affluenzaId;
			}
			set
			{
				this._affluenzaId = value;
			}
		}
		
		private int _sezioneId;
		public virtual int SezioneId
		{
			get
			{
				return this._sezioneId;
			}
			set
			{
				this._sezioneId = value;
			}
		}
		
		private Sezione _sezione;
		public virtual Sezione Sezione
		{
			get
			{
				return this._sezione;
			}
			set
			{
				this._sezione = value;
			}
		}
		
		private Affluenza _affluenza;
		public virtual Affluenza Affluenza
		{
			get
			{
				return this._affluenza;
			}
			set
			{
				this._affluenza = value;
			}
		}
		
	}
}
#pragma warning restore 1591
