#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Scrutinio
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _validi;
		public virtual int Validi
		{
			get
			{
				return this._validi;
			}
			set
			{
				this._validi = value;
			}
		}
		
		private int _nulle;
		public virtual int Nulle
		{
			get
			{
				return this._nulle;
			}
			set
			{
				this._nulle = value;
			}
		}
		
		private int _bianche;
		public virtual int Bianche
		{
			get
			{
				return this._bianche;
			}
			set
			{
				this._bianche = value;
			}
		}
		
		private int _contestate;
		public virtual int Contestate
		{
			get
			{
				return this._contestate;
			}
			set
			{
				this._contestate = value;
			}
		}
		
		private int _sezioneId;
		public virtual int SezioneId
		{
			get
			{
				return this._sezioneId;
			}
			set
			{
				this._sezioneId = value;
			}
		}
		
		private int _consultazioneId;
		public virtual int ConsultazioneId
		{
			get
			{
				return this._consultazioneId;
			}
			set
			{
				this._consultazioneId = value;
			}
		}
		
		private Sezione _sezione;
		public virtual Sezione Sezione
		{
			get
			{
				return this._sezione;
			}
			set
			{
				this._sezione = value;
			}
		}
		
		private Consultazione _consultazione;
		public virtual Consultazione Consultazione
		{
			get
			{
				return this._consultazione;
			}
			set
			{
				this._consultazione = value;
			}
		}
		
	}
}
#pragma warning restore 1591
