#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class SedeElettorale
	{
		private Int _id;
		public virtual Int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _indirizzo;
		public virtual string Indirizzo
		{
			get
			{
				return this._indirizzo;
			}
			set
			{
				this._indirizzo = value;
			}
		}
		
		private string _mappa;
		public virtual string Mappa
		{
			get
			{
				return this._mappa;
			}
			set
			{
				this._mappa = value;
			}
		}
		
		private string _telefono;
		public virtual string Telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				this._telefono = value;
			}
		}
		
		private string _fax;
		public virtual string Fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				this._fax = value;
			}
		}
		
		private string _responsabile;
		public virtual string Responsabile
		{
			get
			{
				return this._responsabile;
			}
			set
			{
				this._responsabile = value;
			}
		}
		
		private Int _circoscrizioneId;
		public virtual Int CircoscrizioneId
		{
			get
			{
				return this._circoscrizioneId;
			}
			set
			{
				this._circoscrizioneId = value;
			}
		}
		
		private Circoscrizione _circoscrizione;
		public virtual Circoscrizione Circoscrizione
		{
			get
			{
				return this._circoscrizione;
			}
			set
			{
				this._circoscrizione = value;
			}
		}
		
		private IList<Sezione> _seziones = new List<Sezione>();
		public virtual IList<Sezione> Seziones
		{
			get
			{
				return this._seziones;
			}
		}
		
	}
}
#pragma warning restore 1591
