#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Sezione
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _votantiMaschi;
		public virtual int VotantiMaschi
		{
			get
			{
				return this._votantiMaschi;
			}
			set
			{
				this._votantiMaschi = value;
			}
		}
		
		private int _votantiFemmine;
		public virtual int VotantiFemmine
		{
			get
			{
				return this._votantiFemmine;
			}
			set
			{
				this._votantiFemmine = value;
			}
		}
		
		private int _totaleVotanti;
		public virtual int TotaleVotanti
		{
			get
			{
				return this._totaleVotanti;
			}
			set
			{
				this._totaleVotanti = value;
			}
		}
		
		private int _sedeElettoraleId;
		public virtual int SedeElettoraleId
		{
			get
			{
				return this._sedeElettoraleId;
			}
			set
			{
				this._sedeElettoraleId = value;
			}
		}
		
		private int _operatoreId;
		public virtual int OperatoreId
		{
			get
			{
				return this._operatoreId;
			}
			set
			{
				this._operatoreId = value;
			}
		}
		
		private SedeElettorale _sedeElettorale;
		public virtual SedeElettorale SedeElettorale
		{
			get
			{
				return this._sedeElettorale;
			}
			set
			{
				this._sedeElettorale = value;
			}
		}
		
		private Operatore _operatore;
		public virtual Operatore Operatore
		{
			get
			{
				return this._operatore;
			}
			set
			{
				this._operatore = value;
			}
		}
		
		private IList<SezioneCollegio> _sezioneCollegios = new List<SezioneCollegio>();
		public virtual IList<SezioneCollegio> SezioneCollegios
		{
			get
			{
				return this._sezioneCollegios;
			}
		}
		
		private IList<Rilevamento> _rilevamentos = new List<Rilevamento>();
		public virtual IList<Rilevamento> Rilevamentos
		{
			get
			{
				return this._rilevamentos;
			}
		}
		
		private IList<ScrutinioCapolista> _scrutinioCapolistas = new List<ScrutinioCapolista>();
		public virtual IList<ScrutinioCapolista> ScrutinioCapolistas
		{
			get
			{
				return this._scrutinioCapolistas;
			}
		}
		
		private IList<Scrutinio> _scrutinios = new List<Scrutinio>();
		public virtual IList<Scrutinio> Scrutinios
		{
			get
			{
				return this._scrutinios;
			}
		}
		
		private IList<ScrutinioLista> _scrutinioListas = new List<ScrutinioLista>();
		public virtual IList<ScrutinioLista> ScrutinioListas
		{
			get
			{
				return this._scrutinioListas;
			}
		}
		
		private IList<ScrutinioCandidato> _scrutinioCandidatos = new List<ScrutinioCandidato>();
		public virtual IList<ScrutinioCandidato> ScrutinioCandidatos
		{
			get
			{
				return this._scrutinioCandidatos;
			}
		}
		
	}
}
#pragma warning restore 1591
