#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataLayer;

namespace DataLayer	
{
	public partial class Sezione
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _votantiMaschi;
		public virtual int VotantiMaschi
		{
			get
			{
				return this._votantiMaschi;
			}
			set
			{
				this._votantiMaschi = value;
			}
		}
		
		private int _votantiFemmine;
		public virtual int VotantiFemmine
		{
			get
			{
				return this._votantiFemmine;
			}
			set
			{
				this._votantiFemmine = value;
			}
		}
		
		private int _totaleVotanti;
		public virtual int TotaleVotanti
		{
			get
			{
				return this._totaleVotanti;
			}
			set
			{
				this._totaleVotanti = value;
			}
		}
		
		private int _sedeElettoraleId;
		public virtual int SedeElettoraleId
		{
			get
			{
				return this._sedeElettoraleId;
			}
			set
			{
				this._sedeElettoraleId = value;
			}
		}
		
		private SedeElettorale _sedeElettorale;
		public virtual SedeElettorale SedeElettorale
		{
			get
			{
				return this._sedeElettorale;
			}
			set
			{
				this._sedeElettorale = value;
			}
		}
		
		private IList<Affluenza> _affluenzas = new List<Affluenza>();
		public virtual IList<Affluenza> Affluenzas
		{
			get
			{
				return this._affluenzas;
			}
		}
		
	}
}
#pragma warning restore 1591
